name: Build & Publish Docker Image

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract frontend metadata for Docker
        id: meta-frontend
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-frontend
          tags: |
            type=sha,format=long
            type=match,pattern=main
            type=raw,value=latest,enable={{is_default_branch}}
          flavor: |
            latest=auto

      - name: Extract backend metadata for Docker
        id: meta-backend
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-backend
          tags: |
            type=sha,format=long
            type=match,pattern=main
            type=raw,value=latest,enable={{is_default_branch}}
          flavor: |
            latest=auto

      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps['meta-frontend'].outputs.tags }}
          labels: ${{ steps['meta-frontend'].outputs.labels }}
          build-args: |
            REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }}

      - name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          context: ./univerityrestapi
          push: true
          tags: ${{ steps['meta-backend'].outputs.tags }}
          labels: ${{ steps['meta-backend'].outputs.labels }}